"""full current schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 17:08:25.986905

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from nwtrack.infra.persistence.orm.types import MonthType

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institutions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("month", MonthType(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency"],
            ["currencies.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "currency", "month", name="uq_exchange_rate_currency_month"
        ),
    )
    op.create_table(
        "account_status_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "inactive", name="status"), nullable=False
        ),
        sa.Column("effective_month", MonthType(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id", "effective_month", name="uq_ash_account_month"
        ),
    )
    op.create_table(
        "account_tags",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("account_id", "tag_id", name="uq_account_tags_account_tag"),
    )
    op.create_table(
        "balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("month", MonthType(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "month", name="uq_balance_account_month"),
    )
    # batch mode reflects the live table to recreate it; an existing legacy
    # database's accounts.status CHECK constraint is unnamed, so it must be
    # passed explicitly here or it is silently dropped during the copy.
    with op.batch_alter_table(
        "accounts",
        schema=None,
        table_args=(
            sa.CheckConstraint(
                "status IN ('active', 'inactive')", name="check_account_status"
            ),
        ),
    ) as batch_op:
        batch_op.add_column(sa.Column("institution_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_accounts_institution_id_institutions",
            "institutions",
            ["institution_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "accounts",
        schema=None,
        table_args=(
            sa.CheckConstraint(
                "status IN ('active', 'inactive')", name="check_account_status"
            ),
        ),
    ) as batch_op:
        batch_op.drop_constraint(
            "fk_accounts_institution_id_institutions", type_="foreignkey"
        )
        batch_op.drop_column("institution_id")

    op.drop_table("balances")
    op.drop_table("account_tags")
    op.drop_table("account_status_history")
    op.drop_table("exchange_rates")
    op.drop_table("tags")
    op.drop_table("institutions")
    # ### end Alembic commands ###
